[package]
name = "survivor_library_script"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humansize = "2.1.3"
once_cell = "1.19.0"
regex = "1.10.2"
reqwest = { version = "0.11.23", features = ["blocking"] }
